device:
  layer: rpi5
  hostname: puddle
  user1: puddle
  # TODO: Random gen this during build
  user1pass: Puddle1!

#ssh:
#  pubkey_only: y
#  pubkey_user1: path/to/key.pub

image:
  name: puddle
  # -- trad layout --
  layer: image-rpios
  boot_part_size: 96M
  root_part_size: 2G
  # -- a/b layout --
  #layer: image-rota
  #boot_part_size: 96M
  #system_part_size: 1G
  #data_part_size: 1G

layer:
  app: puddle-package
  extra: misc-packages
  net: systemd-net-wifi
  config: eeprom-config
  resize: resize-sd-card
  base: trixie-minbase

net:
  wifi_ap_ssid: Puddle
  # TODO: Random gen this during build
  wifi_ap_passphrase: ChangeMe
  #wifi_sta_ssid: Your Network
  #wifi_sta_passphrase: password
