device:
  layer: rpi5
  hostname: puddle
  user1: puddle

image:
  name: puddle
  layer: image-rpios
  boot_part_size: 200%
  root_part_size: 300%

layer:
  app: puddle-package
  base: trixie-minbase

puddle:
  drive: 192.168.2.2
